//GAME LINK.................................................
function startGame() {
    window.location.href = "../chooseMode/chooseScreen.html"
}
//GAME LINK.................................................

//LET...................................................
let startGameButton = document.querySelector('.pixel2');
//LET...................................................

//STARTGAME BUTTON......................................
startGameButton.addEventListener('click', function () {
    startGame();
})
//STARTGAME BUTTON......................................

